Expose Kafka Idempotency Config
openflagr/flagr-archived pull request #45
Opened 2021-10-20 19:18 UTC by fenriskiba

Resolving Issue #21  

## Description
* Upgraded Sarama Version
* Exposed Sarama's new Idempotency config
* Fixed issue with acks not being set properly (prerequisite for Idemptoncy)
* Added config for Kafka MaxOpenRequests (prerequisite for Idemptoncy)

## Motivation and Context
See Issue #21 

## How Has This Been Tested?
Manually regression and stress tested in our OpenShift environment, both with default Kafka configs and Idempotency enabled.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-01 15:49 UTC, fenriskiba commented
@zhouzhuojie or @marceloboeira would one of you be able to review this?

2021-11-03 17:27 UTC, fenriskiba commented
Is there a way to rerun the ci / unit_test suite? It seems like it timed out, but I can't see any reason why it would and it runs fine in my local. I'm wondering if it just got caught on a network issue or something.

2021-11-03 17:53 UTC, marceloboeira commented
@fenriskiba I haven't had the time yet to review this, I'll take a look later this week. In any case, I just re-triggered the jobs to see if it works now

2021-11-04 10:42 UTC, marceloboeira requested changes
Left a few comments of things to do/change but otherwise looks good.

2021-11-04 10:42 UTC, marceloboeira commented on Dockerfile
> +FROM node:14 as npm_builder
Is that something relevant for this PR? I would probably create another one to be easier to track and identify in case we find issues related to this bump....

2021-11-04 10:42 UTC, marceloboeira commented on Dockerfile
> +FROM frolvlad/alpine-glibc:alpine-3.14
same here...

2021-11-04 10:42 UTC, marceloboeira commented on pkg/config/env.go
> +	RecorderKafkaIdempotent     bool          `env:"FLAGR_RECORDER_KAFKA_IDEMPOTENT" envDefault:"false"`
we should probably add this to the documentation, just in case.

2021-11-04 10:42 UTC, marceloboeira commented on pkg/config/env.go
> +	RecorderKafkaMaxOpenReqs    int           `env:"FLAGR_RECORDER_KAFKA_MAXOPENREQUESTS" envDefault:"5"`
is the default set here for max open requests the same from what we currently have? just to avoid any breaking changes...

2021-11-04 13:35 UTC, fenriskiba commented on pkg/config/env.go
> +	RecorderKafkaMaxOpenReqs    int           `env:"FLAGR_RECORDER_KAFKA_MAXOPENREQUESTS" envDefault:"5"`
Yeah, that is the [Sarama default](https://pkg.go.dev/github.com/shopify/sarama#:~:text=//%20How%20many%20outstanding%20requests%20a%20connection%20is%20allowed%20to%20have%20before%0A%09%09//%20sending%20on%20it%20blocks%20(default%205).%0A%09%09MaxOpenRequests%20int) for MaxOpenRequests.
We actually exposed it because it needs to be set to `1` for the Idempotency config to work.

2021-11-04 13:42 UTC, fenriskiba commented on pkg/config/env.go
> +	RecorderKafkaIdempotent     bool          `env:"FLAGR_RECORDER_KAFKA_IDEMPOTENT" envDefault:"false"`
My understanding is that the Env page directly pulls this file. Or are you thinking adding a new section to the docs?

2021-11-04 15:06 UTC, fenriskiba commented on Dockerfile
> +FROM node:14 as npm_builder
I can pull this out and probably submit a new PR for the bump. May not be till next week though, so we can go through our internal review process.

2021-11-04 15:07 UTC, fenriskiba commented on Dockerfile
> +FROM frolvlad/alpine-glibc:alpine-3.14
Would you want these bumps as two separate PRs, or would you be okay with keeping them together?

2021-11-04 15:51 UTC, zhouzhuojie commented on pkg/config/env.go
> +	RecorderKafkaIdempotent     bool          `env:"FLAGR_RECORDER_KAFKA_IDEMPOTENT" envDefault:"false"`
yes doc website serves directly from this file

2021-11-04 15:53 UTC, zhouzhuojie commented
yes, let's separate the docker image bump from Kafka config changes, easy to revert if needed. thank you!

2021-11-04 16:35 UTC, marceloboeira commented on pkg/config/env.go
> +	RecorderKafkaMaxOpenReqs    int           `env:"FLAGR_RECORDER_KAFKA_MAXOPENREQUESTS" envDefault:"5"`
:+1:

2021-11-04 16:35 UTC, marceloboeira commented on pkg/config/env.go
> +	RecorderKafkaIdempotent     bool          `env:"FLAGR_RECORDER_KAFKA_IDEMPOTENT" envDefault:"false"`
great!

2021-11-04 16:36 UTC, marceloboeira commented on Dockerfile
> +FROM frolvlad/alpine-glibc:alpine-3.14
I would say we can have 1 PR with both bumps, should be fine, I don't expect alpine to be an issue tbh, but I'm concerned about node.

2021-11-09 18:25 UTC, zhouzhuojie approved these changes

2021-11-09 18:26 UTC, zhouzhuojie commented on go.mod
> +	github.com/Shopify/sarama v1.29.1
this is a big version bump, any noticeable breaking changes?

2021-11-10 16:22 UTC, fenriskiba commented on go.mod
> +	github.com/Shopify/sarama v1.29.1
The only update I'm aware of that could be breaking is [added SASLVersion in config #1410](https://github.com/Shopify/sarama/pull/1410), though I'll admit, I'm not familiar enough with the SASL Handshake versions work to know how significant that is.

If you think that's a problem/risk, I could change it to v1.20.1. I went with latest (at the time of our internal testing) since I figured staying up to date would be preferable, but the Idempotency configs are back in v1.20.

2021-11-10 19:43 UTC, fenriskiba commented on Dockerfile
> +FROM frolvlad/alpine-glibc:alpine-3.14
Submitted #51 for the image bumps.

2021-11-22 21:48 UTC, zhouzhuojie approved these changes

2021-11-22 21:48 UTC, zhouzhuojie commented
pending on @marceloboeira

2021-11-23 07:52 UTC, marceloboeira approved these changes

2021-11-23 15:21 UTC, merged